const mainVars = {
  breakpoints: {
    mob: '375px',
    mobMax: '767px',
    tab: '768px',
    tabMax: '1439px',
    desk: '1440px',
  },
  fontWeights: {
    s: 400,
    m: 500,
    l: 600,
    xl: 700,
  },
  transitions: {
    main: 'all 250ms cubic-bezier(0.4, 0, 0.2, 1)',
  },
};
export const lightTheme = {
  ...mainVars,
  color: {
    accentStartPage: '#8BAA36',
    titleStartPage: '#FAFAFA',
    title: '#001833',
    primaryTextColor: '#23262A',
    mainTitle: '#22252A',
    text: '#3E4462',
    secondaryTextColor: '#000000',
    accent: '#8BAA36',
    btnColor: '#FAFAFA',
    btnColorSecondary: '#22252A',
    bg: '#FAFAFA',
    bgButtonSelect: '#D9D9D9',
    bgSubscribe: '#8BAA36',
    bgSelectColor: '#FAFAFA',
    bgSecondary: '#22252A',
    bgPagination: '#FAFAFA',
    bgPaginationActive: '#EBF3D4',
    bgAccentEl: '#EBF3D4',
    bgLightEl: '#FFFFFF',
    gbCancel: '#D9D9D9',
    textCancel: '#23262A',
    textSecondary: '#FAFAFA',
    textRights: '#22252A',
    textPagination: '#656565',
    socIcon: '#8BAA36',
    socIconHover: '#FFFFFF',
    logo: '#FAFAFA',
    footerInput: 'rgba(255, 255, 255, 0.3)',
  },
};

export const darkTheme = {
  ...mainVars,
  color: {
    accentStartPage: '#8BAA36',
    titleStartPage: '#FAFAFA',
    title: '#FAFAFA',
    primaryTextColor: '#FAFAFA',
    mainTitle: '#FAFAFA',
    text: '#FAFAFA',
    secondaryTextColor: '#FAFAFA',
    accent: '#8BAA36',
    btnColor: '#FAFAFA',
    btnColorSecondary: '#FAFAFA',
    bg: '#1E1F28',
    bgButtonSelect: '#1E1F28',
    bgSubscribe: '#1E1F28',
    bgSelectColor: '#8BAA36',
    bgSecondary: '#8BAA36',
    bgPagination: '#2A2C36',
    bgPaginationActive: '#8BAA36',
    bgAccentEl: '#2A2C36',
    bgLightEl: '#2A2C36',
    gbCancel: '#D9D9D9',
    textCancel: '#23262A',
    textSecondary: '#FAFAFA',
    textRights: '#8BAA36',
    textPagination: 'rgba(250, 250, 250, 0.6)',
    socIcon: '#FFFFFF',
    socIconHover: '#1E1F28',
    logo: '#FAFAFA',
    footerInput: 'rgba(31, 30, 30, 0.2)',
  },
};
